### PR TITLE
Add config for Romanian bank BCR

### PR DESCRIPTION
**Pull request by rolisz**

### CODE REVIEW

**Comment by JC5** [comment]
The PNG file is 0 bytes, could you verify?

**Comment by rolisz** [comment]
If I click view file, I see the PNG correctly. I think GitHub shows 0 as text lines changed, which is irrelevant for binary files.

**Comment by JC5** [comment]
Indeed. Nice, merged!

**Comment by JC5** [comment]
@allcontributors add @rolisz for content

**Pull request merged**
