### PR TITLE
Added config file for MyWallet expense manager

### PR DESCRIPTION
**Pull request by backmind**
To ETL data from MyWallet database to a csv loadable with this config you can visit the next repo: https://github.com/backmind/MyWallet-to-Fireflyiii

Changes in this pull request:

1. added a config file for the Android app MyWallet

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
There is no role configuration in the file.

**Review by backmind — COMMENTED** [review]
Updated with the actual data (not the mock file).

**Comment by JC5** [comment]
Nice :+1:

**Comment by JC5** [comment]
@allcontributors add @backmind for content

**Comment by JC5** [comment]
@allcontributors add @backmind for content

**Comment by JC5** [comment]
@allcontributors add @backmind for data

**Pull request merged**
