### PR TITLE
Adding Sparkasse Neubrandenburg Demmin Germany with "CSV-MT940 Format…

### PR DESCRIPTION
**Pull request by ichbestimmtnicht**
Adding Sparkasse Neubrandenburg-Demmin Germany with "CSV-MT940 Format" Exportoption

Last row "Buchungstext" is ignored as I am unsure where to put it. "booking earmarked" or "Turnover booked" is the information provided and as it is an information for the moment it seems not necessary.

I don't know how this is handled accross Sparkasse....

### CODE REVIEW

**Comment by JC5** [comment]
You could put it in the "notes" field, perhaps? It will always append so you can have multiple "notes" fields if you want to.

I'll leave this open for a day or two, see what you think. Otherwise I'll merge :+1:

**Comment by ichbestimmtnicht** [comment]
I will change that. 
Should I represent the "CSV-MT940 Format" within the directory structure or the `.json` filename?
These are all export options. I can add them as well If you want to have a greater variety. 
export_options

**Comment by JC5** [comment]
I think that is a good idea, just in case there are future file formats that Firefly III supports.

**Comment by ichbestimmtnicht** [comment]
Directory `neubrandenburg-demmin` to `csv-mt940` or Filename `default.json` to `csv-mt940`?
Or maybe dirictory within `neubrandenburg-demmin`? Whats your favourite layout?

**Comment by JC5** [comment]
`csv-mt940,json` .

**Comment by ichbestimmtnicht** [comment]
You can merge now.

Commit Note: Note that the plain camt file is not useable. Fix: Open it in Calc and save at csv.
```
Sammlerreferenz
Lastschrift Ursprungsbetrag
Auslagenersatz Ruecklastschrift
```
are the ignored entrys 9, 10 and 11 in this order in case you manual adjust them :) Need a translation? Ask me.

**Comment by ichbestimmtnicht** [comment]
Sorry that I forgot to mention the other formats. The 2nd and 3rd (from the foto) are camt with that `Notes` Field only exported for 2 earmarked and 3 booked entrys.
The last to 2 ones are in txt and not importable in an easy way at this time. They are using :NUMBER: as identifier... [Reference](https://www.rabobank.com/en/images/format-description-mt942-2-3-en.pdf)

**Comment by JC5** [comment]
Merged!

**Pull request merged**
