### PR TITLE
Added import config for Volksbank Wildeshauser Geest eG

### PR DESCRIPTION
**Pull request by sebastianklein96**
Changes in this pull request:

- Addition of import config file for Volksbank Wildeshauser Geest eG
- Addition of instructions for sanitizing csv, creating credit / debit indicator handling rule and import procedure

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Do you need a fix for the CSV importer so it'll recognize their debit/credit indicators? Because that's on the table!

**Comment by sebastianklein96** [comment]
Yes, that would be ideal. Maybe only have one debit / credit indicator where you can set a char/string for credit / debit each? It would require a slight UI revamp, but should be possible.

**Comment by JC5** [comment]
That's enough, yep. It doesn't happen that often.

**Comment by sebastianklein96** [comment]
I have made the change in a fork of firefly-iii/csv-importer and opened a pull request.

https://github.com/firefly-iii/csv-importer/pull/8

**Comment by JC5** [comment]
Merged. Also merged this one. Will you keep me up to date when the new CSV version is out. Maybe a change to the JSON file is required.

**Comment by JC5** [comment]
@all-contributors please add sebastianklein96 for data

**Comment by JC5** [comment]
@all-contributors please add @sebastianklein96 for data and content

**Comment by sebastianklein96** [comment]
> Merged. Also merged this one. Will you keep me up to date when the new CSV version is out. Maybe a change to the JSON file is required.

Yes, I will keep an eye on the next release and adapt the json accordingly. Any estimate on when the next minor release will happen?

**Comment by JC5** [comment]
Should be this week, there's nothing that blocks a new release.

**Pull request merged**
