### PR TITLE
Add westpac daily account configuration file

### PR DESCRIPTION
**Pull request by leizhang**
Changes in this pull request:

1.  Add New Zealand Westpac daily account configuration

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Could you fix the extension of the file?

**Comment by leizhang** [comment]
@JC5 Hi James, the extension is fixed now.

**Comment by JC5** [comment]
:+1:

**Comment by JC5** [comment]
@allcontributors add @leizhang for content

**Pull request merged**
