### PR TITLE
Bradesco configuration

### PR DESCRIPTION
**Pull request by gu-does-git**
Changes in this pull request:

Added the Bradesco importer configuration! :+1: 

@JC5

### CODE REVIEW

**Review by JC5 — APPROVED** [review]

**Comment by JC5** [comment]
@allcontributors add @gu-does-git for content

**Comment by JC5** [comment]
Lol idiot

@allcontributors add https://github.com/gu-does-git for content

**Comment by gu-does-git** [comment]
damn hahaha it cant deal with my username

**Comment by JC5** [comment]
Nope lol. But I'm grateful for your contribution regardless!

**Comment by gu-does-git** [comment]
It is I that should be thanking you for FireflyIII tho! :smile: 
I've been using it since 2021 and haven't looked back since, you did a really great job.

**Pull request merged**
