### PR TITLE
Default ING json

### PR DESCRIPTION
**Pull request by tomwerf**
The default ING JSON.
This time I have to commit to the master?

Regards, Tom

### CODE REVIEW

**Comment by JC5** [comment]
That's fine! But some columns could do with a mapping, right?

**Comment by tomwerf** [comment]
I dont understand the usage of the mappings. 

The CSV file has het following fields:
Datum,"Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"

There is one problem with the ING; When the code is BA (Betaalautomaat), the Tegenrekening is empty. So the IBAN numbers are not correctly assigned to the accounts. Only the Account names are assigned.
I dont know if this is a ING problem or a problem for all the banks.

If you want, I can send you an example importfile.

**Comment by JC5** [comment]
Mapping is meant to connect account names from your file, to actual accounts in your database. Take a look at these two accounts as I often encounter them in my files. 

* ALBERT_HE_1246
* AH_TO_GO_UTR_CS

I have both mapped to my pre existing "Albert Heijn" account. I will write about this on the help pages. 

As for the IBAN field: right now, firefly-iii does not "join" the results of a single row. Let's say your import file has three fields. Account name, account IBAN and account number. These three fields point to the same account of course, they are three fields belonging to the same account. But firefly-iii cannot handle this. It will try to find a or create an account for each field separately. This is something that needs to be fixed.

**Comment by tomwerf** [comment]
Thanks for the explaination. I've never used the mappings.
I wil create a new config file with the mapping. And do a new pullrequest when ready.

Maybe for the future it's easier to store the JSON in the database instead of downloading/uploading it.
Than it's easier to start the imports from another computer without making the configs again.

**Comment by JC5** [comment]
Perhaps I will, in time. Before I do, I want the process to be all grown up, without the bugs, problems and issues. Having these configuration files outside of the database isn't perfect, but honestly storing them _in_ the database has its drawbacks too.

Regardless, I will make it a priority to write help files and help pages because most of Firefly has been severely lacking in that regard and its complexity is growing beyond the "use it and you'll get it"-level.

**Comment by tomwerf** [comment]
I understand the priority with the helpfiles and the bugs.
Thanks for sharing your project. It is working great!

**Pull request merged**
