### PR TITLE
Add import configuration for AT/Raiffeisen

### PR DESCRIPTION
**Pull request by weissi1994**
Changes in this pull request:

1. Add JSON for exported data from raiffeisen
2. Add python script to parse more fields
3. Add json to import parsed csv

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Thanks! 

I’m not going to merge the python script, sorry. You can link to it (for example a GitHub gist) but I can’t include it I’m afraid

**Comment by weissi1994** [comment]
Script removed and linked in readme

**Comment by JC5** [comment]
Thanks, appriciate it. Good work on the script! :+1:

**Comment by JC5** [comment]
@allcontributors add @weissi1994 for content

**Pull request merged**
